const { chromium } = require('playwright');
(async()=>{const b=await chromium.launch(); const errs=[]; const ok=(c,m)=>{ console.log((c?'✅ ':'❌ ')+m); if(!c) errs.push(m); };
const p=await b.newPage({viewport:{width:1280,height:900}}); p.on('pageerror',e=>errs.push('pageerror '+e.message)); p.on('dialog',d=>d.accept());
await p.goto('http://localhost:8765/rights-study.html#arena'); await p.waitForTimeout(800);
for(const id of ['f11','f21','f22','f23','f31','f32','f41','f42','f51','f54','f61','f63','f53','f64']){
  const r=await p.evaluate(async(id)=>{ localStorage.clear(); const c=kcRec(); delete c.life; c.fr={full:true}; c.cash=900000; page='arena'; arenaTab='king'; KC_MODE='career'; K_PROP_NEXT=id; KC_INTRO=false; kStart(5); K.intro=false;
    const u={}; for(const e of ['normal','angry','worried']) u[e]=artNpc(KP.occ.pid,e);
    const own=['normal','angry','worried'].every(e=>u[e]===artUrl('npc_occ_'+id+'_'+e));
    const loads=await Promise.all(Object.values(u).map(s=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>100); i.onerror=()=>r(false); i.src=s; })));
    const distinct=new Set(Object.values(u)).size;
    return {own, loads:loads.every(Boolean), distinct, name:KP.occ.name}; },id);
  ok(r.own && r.loads && r.distinct===3, id+' '+r.name+' — 전용 그림 3표정이 무대에 뜸');
}
// 자유 플레이 같은 pid는 원래 그림
const r=await p.evaluate(()=>{ K=null; return [artNpc('p_madam','normal'), artNpc('p_greedy','normal')].map(u=>Object.values(AS_OCC_ART).some(id=>u&&u.includes(id))); });
ok(!r[0] && !r[1], '물건 밖(자유 플레이)은 원래 그림 그대로');
// 오프닝 전용 그림 — 33칸 전부
const o=await p.evaluate(async()=>{ const ks=ART_SLOTS_V135.filter(x=>x.id.startsWith('op_')).map(x=>x.id); const us=ks.map(k=>artUrl(k));
  const loads=await Promise.all(us.map(s=>new Promise(r=>{ if(!s) return r(false); const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=s; })));
  return {n:ks.length, ok:loads.filter(Boolean).length, distinct:new Set(us).size, miss:ks.filter((k,i)=>!loads[i])}; });
ok(o.n===33 && o.ok===33 && o.distinct===33, '오프닝 33칸 전부 전용 그림이 로드됨 (빠진 칸: '+o.miss.join(',')+')');
// 물건 전용 배경 — f11 첫 세트
const g=await p.evaluate(async()=>{ localStorage.clear(); const c=kcRec(); delete c.life; c.fr={full:true}; page='arena'; arenaTab='king'; KC_MODE='career'; K_PROP_NEXT='f11'; KC_INTRO=false; kStart(5); K.intro=false;
  const pick=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s));
  const loads=await Promise.all(pick.map(k=>new Promise(r=>{ const u=artUrl(k); if(!u) return r(false); const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=u; })));
  K_PROP_NEXT='f64'; kStart(5); K.intro=false; const other=vnBgPick('bg_front_door');
  return {pick, loads, other}; });
ok(g.pick.join()==='bg_case_f11_ext,bg_case_f11_door,bg_case_f11_in' && g.loads.every(Boolean), 'f11 조사·명도·빈집 장면이 전용 배경 3장으로 바뀜');
ok(g.other==='bg_front_door', '배경이 아직 없는 물건(f64)은 원래 공용 배경 그대로');
const g2=await p.evaluate(()=>{ K_PROP_NEXT='f12'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g2.join()==='bg_case_f12_ext,bg_case_f12_door,bg_case_f12_in', 'f12 외관·복도·빈 원룸 전용 배경 3장');
const g3=await p.evaluate(()=>{ K_PROP_NEXT='f13'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g3.join()==='bg_case_f13_ext,bg_case_f13_door,bg_case_f13_in', 'f13 전용 배경 3장');
const g4=await p.evaluate(()=>{ K_PROP_NEXT='f21'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g4.join()==='bg_case_f21_ext,bg_case_f21_door,bg_room_empty', 'f21 외관·현관 전용, 거실 칸은 아직 공용 배경');
const g5=await p.evaluate(()=>{ K_PROP_NEXT='f22'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g5.join()==='bg_case_f22_ext,bg_case_f22_door,bg_case_f22_in', 'f22 전용 배경 3장');
const g6=await p.evaluate(()=>{ K_PROP_NEXT='f23'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g6.join()==='bg_case_f23_ext,bg_case_f23_door,bg_case_f23_in', 'f23 전용 배경 3장');
const g7=await p.evaluate(()=>{ K_PROP_NEXT='f31'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); });
ok(g7.join()==='bg_case_f31_ext,bg_case_f31_door,bg_room_empty', 'f31 외관·미용실 입구 전용, 빈 가게 칸은 공용 배경');
const g8=await p.evaluate(()=>{ K_PROP_NEXT='f32'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_villa_night','bg_front_door','bg_stairs','bg_room_messy','bg_room_empty'].map(s=>vnBgPick(s)); K.repair={id:'min'}; a.push(vnBgPick('bg_room_empty')); K.repair=null; return a; });
ok(g8.slice(0,6).join()==='bg_case_f32_ext,bg_case_f32_ext,bg_case_f32_door,bg_case_f32_door,bg_case_f32_in,bg_case_f32_in' && g8[6]!=='bg_case_f32_in', 'f32 중식당 외관·홀·주방 전용(수리 단계 빈집은 공용)');
const l8=await p.evaluate(async()=>Promise.all(['ext','door','in'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f32_'+k); }))));
ok(l8.every(Boolean), 'f32 배경 3장 로드');
const g9=await p.evaluate(()=>{ const out={}; for(const id of ['f33','f34']){ K_PROP_NEXT=id; kStart(5); K.intro=false; out[id]=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)).join(); } return out; });
ok(g9.f33==='bg_case_f33_ext,bg_case_f33_door,bg_case_f33_in' && g9.f34==='bg_case_f34_ext,bg_case_f34_door,bg_case_f34_in', 'f33·f34 외관·현관·실내 전용');
const l9=await p.evaluate(async()=>Promise.all(['f33_ext','f33_door','f33_in','f34_ext','f34_door'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_'+k); }))));
ok(l9.every(Boolean), 'f33·f34 배경 5장 로드');
const g10=await p.evaluate(()=>{ const out={}; for(const id of ['f41','f42']){ K_PROP_NEXT=id; kStart(5); K.intro=false; out[id]=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)).join(); } return out; });
ok(g10.f41==='bg_case_f41_ext,bg_case_f41_door,bg_case_f41_in' && g10.f42==='bg_case_f42_ext,bg_case_f42_door,bg_case_f42_in', 'f41·f42 3장 전용');
const l10=await p.evaluate(async()=>Promise.all(['f34_in','f41_ext','f41_door','f41_in','f42_ext','f42_door'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_'+k); }))));
ok(l10.every(Boolean), 'f34·f41·f42 배경 6장 로드');
const g11=await p.evaluate(()=>{ const out={}; for(const id of ['f43','f44']){ K_PROP_NEXT=id; kStart(5); K.intro=false; out[id]=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)).join(); } return out; });
ok(g11.f43==='bg_case_f43_ext,bg_case_f43_door,bg_case_f43_in' && g11.f44==='bg_case_f44_ext,bg_case_f44_door,bg_case_f44_in', 'f43·f44 3장 전용');
const l11=await p.evaluate(async()=>Promise.all(['f42_in','f43_ext','f43_door','f43_in','f44_ext'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_'+k); }))));
ok(l11.every(Boolean), 'f42·f43·f44 배경 5장 로드');
const g12=await p.evaluate(()=>{ K_PROP_NEXT='f51'; kStart(5); K.intro=false; return ['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)).join(); });
ok(g12==='bg_case_f51_ext,bg_case_f51_door,bg_case_f51_in', 'f51 3장 전용');
const l12=await p.evaluate(async()=>Promise.all(['f44_door','f44_in','f51_ext','f51_door'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_'+k); }))));
ok(l12.every(Boolean), 'f44·f51 배경 4장 로드');
const g13=await p.evaluate(()=>{ const out={}; for(const id of ['f52','f53']){ K_PROP_NEXT=id; kStart(5); K.intro=false; out[id]=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)).join(); } return out; });
ok(g13.f52==='bg_case_f52_ext,bg_case_f52_door,bg_case_f52_in' && g13.f53==='bg_case_f53_ext,bg_case_f53_door,bg_case_f53_in', 'f52·f53 3장 전용');
const l13=await p.evaluate(async()=>Promise.all(['f51_in','f52_ext','f52_door','f52_in','f53_ext','f53_door','f53_in'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_'+k); }))));
ok(l13.every(Boolean), 'f51·f52·f53 배경 5장 로드');
const g14=await p.evaluate(async()=>{ K_PROP_NEXT='f54'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); const ok=await new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f54_ext'); }); return {a:a.join(), ok}; });
ok(g14.a.startsWith('bg_case_f54_ext,') && !g14.a.includes('f54_door') && g14.ok, 'f54 외관 전용(현관·실내는 공용) + 로드');
const g15=await p.evaluate(async()=>{ K_PROP_NEXT='f61'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); const ok=await new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f61_ext'); }); return {a:a.join(), ok}; });
ok(g15.a.startsWith('bg_case_f61_ext,') && g15.a.endsWith(',bg_case_f61_in') && !g15.a.includes('f61_door') && g15.ok, 'f61 외관·실내 전용 + 로드');
const g16=await p.evaluate(async()=>{ K_PROP_NEXT='f62'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); const ok=await Promise.all(['ext','in'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f62_'+k); }))); return {a:a.join(), ok:ok.every(Boolean)}; });
ok(g16.a.startsWith('bg_case_f62_ext,') && g16.a.endsWith(',bg_case_f62_in') && !g16.a.includes('f62_door') && g16.ok, 'f62 외관·실내 전용 + 로드');
const g17=await p.evaluate(async()=>{ K_PROP_NEXT='f63'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); const ok=await new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f63_ext'); }); const ok2=await Promise.all(['door','in'].map(k=>new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f63_'+k); }))); return {a:a.join(), ok:ok&&ok2.every(Boolean)}; });
ok(g17.a==='bg_case_f63_ext,bg_case_f63_door,bg_case_f63_in' && g17.ok, 'f63 3장 전용 + 로드');
const g18=await p.evaluate(async()=>{ K_PROP_NEXT='f64'; kStart(5); K.intro=false; const a=['bg_villa_day','bg_front_door','bg_room_empty'].map(s=>vnBgPick(s)); const ok=await new Promise(r=>{ const i=new Image(); i.onload=()=>r(i.naturalWidth>1000); i.onerror=()=>r(false); i.src=artUrl('bg_case_f64_ext'); }); return {a:a.join(), ok}; });
ok(g18.a==='bg_case_f64_ext,bg_front_door,bg_room_empty' && g18.ok, 'f64 외관 전용 + 로드(문·실내는 공용)');
ok(!errs.some(e=>e.startsWith('pageerror')), 'JS 오류 없음');
console.log(errs.length?'FAIL':'ALL OK'); await b.close(); })();
